In [3]:
!python --version

Python 3.12.6

In [5]:
pip install pyspellchecker pandas

Requirement already satisfied: pyspellchecker in .\anaconda3\envs\nlp_env\Lib\site-packages (0.9.0)
Collecting pandas
  Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.1-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\envs\nlp_env\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\anaconda3\envs\nlp_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp312-cp312-win_amd64.whl (9.8 MB)
Using cached numpy-2.5.1-cp312-cp312-win_amd64.whl (12.4 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.1 pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

In [12]:
import pandas as pd

file = "malindo_dic_2024.tsv"
column = [
    
    "id",
    "root",          # Akar
    "surface",       # Bentuk lahir
    "prefix",        # Awalan/proklitik
    "suffix",        # Akhiran/enklitik
    "circumfix",     # Apitan
    "reduplication", # Penggandaan
    "source",        # Sumber
    "stem",          # Dasar
    "lemma",         # Lema
]
df = pd.read_csv(
    file, 
    sep = "\t",
    names = column,
    encoding = "utf-8"
)

df.head(5)

,id,root,surface,prefix,suffix,circumfix,reduplication,source,stem,lemma
0,cc-1,'iṭfatur-raḥmān,'iṭfatur-raḥmān,0,0,0,0,Kamus,'iṭfatur-raḥmān,'iṭfatur-raḥmān
1,cc-2,-an,-an,0,0,0,0,Kamus,-an,-an
2,cc-3,-anda,-anda,0,0,0,0,Kamus,-anda,-anda
3,cc-4,-asi,-asi,0,0,0,0,Kamus,-asi,-asi
4,cc-5,-da,-da,0,0,0,0,Kamus,-da,-da

In [19]:
words = input(str("Words: "))

## Words Error checking
output = df.loc[df["surface"] == words.lower()]
output

Words:  baca

,id,root,surface,prefix,suffix,circumfix,reduplication,source,stem,lemma
9139,cc-9140,baca,baca,0,0,0,0,Kamus,baca,membaca

In [49]:
import re

sentences = input(str("Sentences: "))
list_of_words = []
output = [] # need to return array of array

def tokenize(sentences):
    result = re.sub(r'[^\w\s]', '', sentences)
    result = re.split(r'\s+', result)
    return result # return array

for word in tokenize(sentences):
    grammar = df.loc[df["surface"] == word.lower()] # return dataframe
    list_of_words.append(grammar)

for item in list_of_words:
    output.append({
        "Word": item["surface"].to_string(index=False),
        "Root": item["root"].to_string(index=False),
        "Prefix": item["prefix"].to_string(index=False),
        "Suffix": item["suffix"].to_string(index=False),
        "circumfix": item["circumfix"].to_string(index=False),
        "Lemma": item["lemma"].to_string(index=False),
    })
    
print(type(output))
for i in range(len(output)):
    print(output[i])

Sentences:  ali membaca buku mengepamkan

<class 'list'>
{'Word': 'ali', 'Root': 'ali', 'Prefix': '0', 'Suffix': '0', 'circumfix': '0', 'Lemma': 'mengali'}
{'Word': 'membaca', 'Root': 'baca', 'Prefix': 'meN-', 'Suffix': '0', 'circumfix': '0', 'Lemma': 'membaca'}
{'Word': 'buku', 'Root': 'buku', 'Prefix': '0', 'Suffix': '0', 'circumfix': '0', 'Lemma': 'buku'}
{'Word': 'mengepamkan', 'Root': 'pam', 'Prefix': 'meN-', 'Suffix': '-kan', 'circumfix': '0', 'Lemma': 'mengepamkan'}